name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Resource Pack
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "Builder[bot]"
        git config --global user.email "mail@unmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
    - name: Update Hash
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        hash=$(sha1sum release.zip)
        ftp -inv $HOST <<EOF
        user $USERNAME $PASSWORD
        get server.properties
        bye
        EOF
        sed -i "/resource-pack-sha1=/c\resource-pack-sha1=$hash" server.properties
        ftp -inv $HOST <<EOF
        user $USERNAME $PASSWORD
        mput server.properties
        bye
        EOF
        rm server.properties
