name: Squash
on:
  push:
    tags:
      - '**'
jobs:
  squash:
    runs-on: ubuntu-20.04
    environment: Resource Pack
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run PackSquash
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        artifact_name: pack
        packsquash_version: latest
        options: |
          # Set a custom output file path to work with the generated ZIP file
          # without needing to download its artifact in a separate step
          output_file_path = '/tmp/pack.zip'
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: /tmp/pack.zip
  # release:
  #   needs: [squash]
  #   runs-on: ubuntu-20.04
  #   environment: Resource Pack
  #   steps:
  #   - name: Fetch Github Release Asset
  #     uses: dsaltares/fetch-gh-release-asset@1.1.1
  #     with:
  #       file: pack.zip
  #       target: pack.zip