name: Squash
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Resource Pack
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Run PackSquash
      uses: ComunidadAylas/PackSquash-action@v3
    - name: Download optimized pack
      uses: actions/download-artifact@v3
      with:
          name: Optimized pack
