name: Squash
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Resource Pack
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run PackSquash
      uses: ComunidadAylas/PackSquash-action@v3
      with:
        artifact_name: Pack
        transcode_ogg: false
    - name: Download optimized pack
      uses: actions/download-artifact@v3
      with:
        name: Optimized pack
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: pack.zip
